name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        type: string
        pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create changelog diff
        run: |
          sed -n '/#### [${{ inputs.version }}]/,/^#### /p' CHANGELOG.md | sed '$d' > release_notes.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body_path: ./release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete release_notes file
        run: rm release_notes.md
