[build-system]
requires = ["pdm-backend", "flask", "sqlalchemy", "sqlalchemy_json"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.coverage]
run.branch = true
run.source = ["project_tracking"]

[project]
name = "project_tracking"
dynamic = ["version"]
authors = [
  { name="P-O Quirion", email="po.quirion@mcgill.ca" },
  { name="Paul Streteowich", email="paul.stretenowich@mcgill.ca" },
]
description = "API and DB to track C3G assembler"
readme = "README.md"
requires-python = ">=3.10.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "flask>=2.2.2",
    "sqlalchemy>=2.0.25",
    "alembic>=1.13.1",
    "alembic-utils",
    "alembic-postgresql-enum",
    "gunicorn>=20.1.0",
    "marshmallow",
    "marshmallow-sqlalchemy"
]

[project.urls]
"Homepage" = "https://github.com/C3G/project_tracking"
"Bug Tracker" = "https://github.com/pypa/project_tracking/issues"

[project.optional-dependencies]
tests = [
  "pytest",
  "coverage",
]
postgres = [
  "psycopg2-binary",
]

[tool.pdm]
allow-direct-references = true

[tool.pdm.version]
source = "file"
path = "project_tracking/__version__.py"
# source = "scm"
# version_format = "project_tracking.version:format_version"
# write_to = "project_tracking/__version__.py"
# write_template = "__version__ = '{}'"
