name: Dev Container Publish

on:
  push:
    branches:
      - dev

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pdm install --prod --no-lock --no-editable

      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Call reusable Docker publish workflow
        uses: ./.github/workflows/reusable-docker-publish.yml
        with:
          image_name: ${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}:dev
            ghcr.io/${{ github.repository }}:dev-${{ steps.vars.outputs.short_sha }}
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
