name: Run PyTest

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['dev', 'main']
  push:
    branches: ['main']

jobs:
  test-and-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pdm install -d -G testing

    - name: Run Tests
      run: |
        pdm run -v pytest tests
