name: Docker Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tags:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64
      dockerfile:
        required: false
        type: string
        default: ./Containerfile
      context:
        required: false
        type: string
        default: .
    secrets:
      token:
        required: true

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update package lists
        run: sudo apt-get update

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          sbom: true
          provenance: true
          tags: ${{ inputs.tags }}
          platforms: ${{ inputs.platforms }}
